export const GET_TODOLIST = 'GET_TODOLIST';
export const ADD_TO_TODOLIST = 'ADD_TO_TODOLIST';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CHANGE_ITEM = 'CHANGE_ITEM';
export const ENSURE_CHANGE = 'ENSURE_CHANGE';
export const CANCEL_DIALOG = 'CANCEL_DIALOG';
